### ISSUE TITLE
Release_Date format for PRJNA209566 is incorrect

### ISSUE THREAD

**Issue by codemeleon** [riboseqorg/RiboSeqOrg-DataPortal#120]
Release_Date  for PRJNA209566 is "1/01/01 00:00" which is not in format of "YYYY/MM/DD hh:mm".

**Comment by JackCurragh** [comment]
Found where this originated: [see here](https://github.com/riboseqorg/RiboSeqOrg-DataPortal/blob/0f9d2660f569022684fe330bb9996d0abc69ea21/scripts/populate_study_metainfo_dict.py#L166)
